kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    name: html-openshift-app
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
type: kubernetes.io/basic-auth
stringData:
  username: "bi-it-bee"
  password: "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"
 
---
kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-generic-webhook-secret
  labels:
    name: html-openshift-app
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
type: Opaque
data:
  WebHookSecretKey: Ym9zbWFrZXJha2lzaW55ZWFoYXQ=