apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: html-openshift-app
  namespace: 254500-emmber
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'ghcr.io/bi-it-bee/html-openshift-app'